#This is the external configuration
user:
  service:
    web:
      domain:
        url: https://prettylogin-17498.web.app/
    cors:
      allowed: "*"
    api:
      key: 123456
    from:
        email: DevSanCabo's Material UI Login Page at Prod
spring:
  mail:
    username: altrem23@gmail.com
    password: jfherre52121

logging:
  level:
    org:
      springframework:
        web: DEBUG